id: P009418
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5186
  title: ལེགས་བཤད་གཅེས་བཏུས།
  author: ''
  volumes:
    00e21f18193b4cd09854b82940e82fb9:
      image_group_id: I3CN5188
      title: ''
      volume_number: 1
      total_pages: 541
      base_file: v001.txt
