id: IB18F8CF7
legacy_id: P009418
ocr_import_info:
  bdrc_scan_id: W3CN5186
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T22:09:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:53:10.002915+00:00'
last_modified: 2022-09-03 22:53:22.309175
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5186
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5186
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལེགས་བཤད་གཅེས་བཏུས།
  author: གུང་ཐང་བསྟན་པའི་སྒྲོན་མེ།
statistics:
  ocr_word_mean_confidence_index: 0.9489569728996167
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5188:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5188
      total_pages: 541
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5188.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9489569728996167
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
